### ISSUE TITLE
History sheet: Marking of Last NZ address doesn't seem to be there.

### ISSUE THREAD

**Issue by EvanRobertsNZ** [simensta/scribeAPI#2]
![screen shot 2015-07-29 at 3 17 01 pm](https://cloud.githubusercontent.com/assets/11081880/8968780/008ffdd2-3605-11e5-8e5a-e5c5a2363191.png)

**Comment by simensta** [comment]
@EvanRobertsNZ: added the Last New Zealand address field and a field for Religion.
