### ISSUE TITLE
Return on multi-line answers

### ISSUE THREAD

**Issue by EvanRobertsNZ** [simensta/scribeAPI#7]
On multi-line answers (e.g. next of kin and address on History sheets) pressing return while entering the response does not enter a line break, but exits the dialog for entering response. I think we'll lose some data this way (or at least not get it entered).

**Comment by simensta** [comment]
Added this solution. Let me know if you find other fields that needs this particular multi-line transcription tool. 
![new_line_example](https://cloud.githubusercontent.com/assets/7684729/9178937/fcc0497e-3f5e-11e5-9678-2765627c10a4.png)

**Comment by EvanRobertsNZ** [comment]
The address one below. How will this show up in the data? With a line break
character?


On 10 August 2015 at 12:56, simensta <notifications@github.com> wrote:

> Added this solution. Let me know if you find other fields that needs this
> particular multi-line transcription tool.
> [image: new_line_example]
> <https://cloud.githubusercontent.com/assets/7684729/9178937/fcc0497e-3f5e-11e5-9678-2765627c10a4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simensta/scribeAPI/issues/7#issuecomment-129549284>.
>



-- 

Evan Roberts
Assistant Professor, University of Minnesota
eroberts@umn.edu
http://www.evanroberts.net/

**Comment by simensta** [comment]
The above transcription is stored as: `"value" : "Tarras\nOtago Central"`. The `\n` indicates a line break. Will that data format work?

**Comment by EvanRobertsNZ** [comment]
Yes, that will work great. Regular expressions are powerful :)

On 10 August 2015 at 13:40, simensta <notifications@github.com> wrote:

> Reopened #7 <https://github.com/simensta/scribeAPI/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simensta/scribeAPI/issues/7#event-378315470>.
>



-- 

Evan Roberts
Assistant Professor, University of Minnesota
eroberts@umn.edu
http://www.evanroberts.net/
